apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-gateway
  labels:
    app: baas-gateway-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: baas-gateway-service
    spec:
      containers:
      - name: baas-gateway-service
        image: gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8000

